services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: form_app
    environment:
      NODE_ENV: development
      PORT: 3000

      # Connexion à MySQL LOCAL
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:  # vide si tu n'as pas de mot de passe
      DB_NAME: form_db

    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - form-network

networks:
  form-network: